Repository roc-streaming/roc-toolkit, pull requests merged in 2019-10, with the labels that each got.

#265 Implement backtrace printing for non-glibc targets
  SConstruct
  scripts/3rdparty.py
  src/modules/roc_core/target_bionic/roc_core/backtrace.cpp
  src/modules/roc_core/target_libunwind/roc_core/backtrace.cpp
  src/modules/roc_core/target_nobacktrace/roc_core/backtrace.cpp
Labels: contrib

#273 Colored logs (#272)
  src/modules/roc_core/target_posix/roc_core/colors.cpp
  src/modules/roc_core/target_posix/roc_core/colors.h
  src/modules/roc_core/target_stdio/roc_core/log.cpp
  src/modules/roc_core/target_stdio/roc_core/log.h
  src/tools/roc_conv/cmdline.ggo
  src/tools/roc_conv/main.cpp
  src/tools/roc_recv/cmdline.ggo
  src/tools/roc_recv/main.cpp
  src/tools/roc_send/cmdline.ggo
  src/tools/roc_send/main.cpp
Labels: contrib

#247 Add multicast support
  docs/sphinx/manuals/roc_recv.rst
  src/lib/include/roc/address.h
  src/lib/src/address.cpp
  src/modules/roc_netio/target_libuv/roc_netio/udp_receiver_port.cpp
  src/modules/roc_netio/target_libuv/roc_netio/udp_receiver_port.h
  src/modules/roc_packet/parse_address.cpp
  src/modules/roc_packet/parse_address.h
  src/modules/roc_packet/target_posix/roc_packet/address.cpp
  src/modules/roc_packet/target_posix/roc_packet/address.h
  src/modules/roc_packet/target_stdio/roc_packet/address_to_str.cpp
  src/modules/roc_pipeline/target_stdio/roc_pipeline/parse_port.cpp
  src/tests/roc_lib/test_sender_receiver.cpp
  src/tests/roc_netio/test_transceiver.cpp
  src/tests/roc_netio/test_udp.cpp
  src/tests/roc_packet/test_address.cpp
  src/tests/roc_packet/test_parse_address.cpp
  src/tests/roc_pipeline/test_helpers.h
  src/tools/roc_recv/cmdline.ggo
  src/tools/roc_recv/main.cpp
  src/tools/roc_send/main.cpp
Labels: ready for review

#279 Enable colorful logs in tests
  src/tests/test_main.cpp
Labels: tests

#280 Extract and reuse string helpers
  src/modules/roc_address/io_uri_format.cpp
  src/modules/roc_address/io_uri_parse.rl
  src/modules/roc_address/socket_addr_to_str.cpp
  src/modules/roc_address/socket_addr_to_str.h
  src/modules/roc_address/target_stdio/roc_address/socket_addr_to_str.cpp
  src/modules/roc_core/string_utils.cpp
  src/modules/roc_core/string_utils.h
  src/modules/roc_core/target_libunwind/roc_core/backtrace.cpp
  src/tests/roc_core/test_string_utils.cpp
Labels: ready for review
