Repository roc-streaming/roc-toolkit, pull requests merged in 2023-11, with the labels that each got.

#622 Remove unnecessary `explicit`
  src/internal_modules/roc_audio/pcm_mapper.h
Labels: ready for review

#620 GH-303 Ensure implementations of packet::IReader use ROC_ATTR_NODISCARD
  src/internal_modules/roc_fec/reader.h
  src/internal_modules/roc_packet/concurrent_queue.h
  src/internal_modules/roc_packet/delayed_reader.h
  src/internal_modules/roc_packet/queue.h
  src/internal_modules/roc_packet/sorted_queue.h
  src/internal_modules/roc_rtp/populator.h
  src/internal_modules/roc_rtp/timestamp_injector.h
  src/internal_modules/roc_rtp/validator.h
  src/tests/roc_audio/test_depacketizer.cpp
  src/tests/roc_fec/test_writer_reader.cpp
  src/tests/roc_packet/test_delayed_reader.cpp
  src/tests/roc_rtp/test_helpers/status_reader.h
Labels: ready for review

#625 Add lengths to StringList
  src/internal_modules/roc_core/string_list.cpp
  src/internal_modules/roc_core/string_list.h
  src/internal_modules/roc_sndio/backend_dispatcher.cpp
  src/tests/roc_core/test_string_list.cpp
Labels: needs revision, contribution, hacktoberfest-accepted

#642 print_supported implemented for recv and send tools.
  src/internal_modules/roc_address/print_supported.cpp
  src/internal_modules/roc_address/print_supported.h
  src/internal_modules/roc_address/protocol_map.cpp
  src/internal_modules/roc_address/protocol_map.h
  src/internal_modules/roc_sndio/print_supported.cpp
  src/tools/roc_recv/main.cpp
  src/tools/roc_send/main.cpp
Labels: ready for review, contribution

#650 Remove unused header
  src/internal_modules/roc_pipeline/sender_endpoint.h
Labels: ready for review

#649 Update outdated log message
  src/internal_modules/roc_pipeline/sender_session.cpp
Labels: ready for review

#647 gh-303 Reduce number of status checks in tests
  src/tests/roc_fec/test_writer_reader.cpp
Labels: ready for review

#621 Refactor ChannelMapper
  src/internal_modules/roc_audio/channel_mapper.cpp
  src/internal_modules/roc_audio/channel_mapper.h
  src/internal_modules/roc_audio/channel_mapper_matrix.cpp
  src/internal_modules/roc_audio/channel_mapper_matrix.h
Labels: ready for review

#626 Minor refactoring of channel mapping
  src/internal_modules/roc_audio/channel_mapper.cpp
  src/internal_modules/roc_audio/channel_mapper.h
  src/internal_modules/roc_audio/channel_mapper_matrix.cpp
  src/internal_modules/roc_audio/channel_mapper_matrix.h
  src/internal_modules/roc_audio/channel_mapper_table.cpp
  src/internal_modules/roc_audio/channel_mapper_table.h
  src/internal_modules/roc_audio/channel_set.cpp
  src/tests/roc_audio/test_channel_mapper.cpp
  src/tests/roc_audio/test_channel_mapper_table.cpp
  src/tests/roc_audio/test_channel_set.cpp
  src/tests/roc_audio/test_sample_spec.cpp
Labels: ready for review

#643 Configurable limits - Refactor current options
  src/internal_modules/roc_core/parse_units.cpp
  src/internal_modules/roc_core/parse_units.h
  src/tests/roc_core/test_parse_duration.cpp
  src/tests/roc_core/test_parse_units.cpp
  src/tools/roc_copy/main.cpp
  src/tools/roc_recv/cmdline.ggo
  src/tools/roc_recv/main.cpp
  src/tools/roc_send/cmdline.ggo
  src/tools/roc_send/main.cpp
Labels: ready for review, contribution

#631 Add four CTS tests
  src/tests/roc_audio/test_depacketizer.cpp
  src/tests/roc_audio/test_packetizer.cpp
  src/tests/roc_audio/test_resampler.cpp
Labels: ready for review, needs rebase
