Repository roc-streaming/roc-toolkit, pull requests merged in 2023-10, with the labels that each got.

#589 Extracted non-templated code out of RefCounted
  src/internal_modules/roc_core/ref_counted.h
  src/internal_modules/roc_core/ref_counted_impl.cpp
  src/internal_modules/roc_core/ref_counted_impl.h
Labels: ready for review, contribution

#590 GH-303 Avoid pointer usage
  src/internal_modules/roc_pipeline/sender_endpoint.cpp
  src/internal_modules/roc_pipeline/sender_endpoint.h
Labels: ready for review

#585 Slab pool boundary guard
  src/internal_modules/roc_audio/poison_reader.cpp
  src/internal_modules/roc_core/heap_arena.cpp
  src/internal_modules/roc_core/memory_ops.cpp
  src/internal_modules/roc_core/memory_ops.h
  src/internal_modules/roc_core/poison_ops.cpp
  src/internal_modules/roc_core/poison_ops.h
  src/internal_modules/roc_core/pool.h
  src/internal_modules/roc_core/pool_impl.cpp
  src/internal_modules/roc_core/pool_impl.h
  src/tests/roc_core/test_pool.cpp
Labels: ready for review, contribution

#593 Extracted MpscQueueImpl class from MpscQueue
  src/internal_modules/roc_core/mpsc_queue.h
  src/internal_modules/roc_core/mpsc_queue_impl.cpp
  src/internal_modules/roc_core/mpsc_queue_impl.h
Labels: needs revision

#594 Slab pool ownership guard
  src/internal_modules/roc_core/pool.h
  src/internal_modules/roc_core/pool_impl.cpp
  src/internal_modules/roc_core/pool_impl.h
  src/tests/roc_core/test_pool.cpp
Labels: ready for review, contribution

#597 Heap arena canary guards
  src/internal_modules/roc_core/heap_arena.cpp
  src/internal_modules/roc_core/heap_arena.h
  src/tests/bench_main.cpp
  src/tests/roc_core/test_heap_arena.cpp
  src/tests/test_main.cpp
  src/tools/roc_copy/main.cpp
  src/tools/roc_recv/main.cpp
  src/tools/roc_send/main.cpp
Labels: needs revision, contribution

#596 Implement lock-free fast_random function
  src/internal_modules/roc_audio/packetizer.cpp
  src/internal_modules/roc_core/fast_random.cpp
  src/internal_modules/roc_core/fast_random.h
  src/internal_modules/roc_core/target_posix/roc_core/fast_random.cpp
  src/internal_modules/roc_fec/writer.cpp
  src/internal_modules/roc_packet/interleaver.cpp
  src/internal_modules/roc_rtcp/session.cpp
  src/tests/roc_core/bench_random.cpp
  src/tests/roc_core/test_fast_random.cpp
  src/tests/roc_ctl/bench_task_queue_contention.cpp
  src/tests/roc_fec/test_encoder_decoder.cpp
  src/tests/roc_netio/test_helpers/conn_reader.h
  src/tests/roc_netio/test_helpers/conn_writer.h
  src/tests/roc_pipeline/bench_pipeline_loop_peak_load.cpp
Labels: needs revision, contribution

#570 GH-303 Add support for status codes in packet reader
  SConstruct
  src/internal_modules/roc_audio/depacketizer.cpp
  src/internal_modules/roc_error/error_code.h
  src/internal_modules/roc_error/error_code_to_str.cpp
  src/internal_modules/roc_error/error_code_to_str.h
  src/internal_modules/roc_fec/reader.cpp
  src/internal_modules/roc_fec/reader.h
  src/internal_modules/roc_node/sender_encoder.cpp
  src/internal_modules/roc_node/sender_encoder.h
  src/internal_modules/roc_packet/concurrent_queue.cpp
  src/internal_modules/roc_packet/concurrent_queue.h
  src/internal_modules/roc_packet/delayed_reader.cpp
  src/internal_modules/roc_packet/delayed_reader.h
  src/internal_modules/roc_packet/ireader.h
  src/internal_modules/roc_packet/queue.cpp
  src/internal_modules/roc_packet/queue.h
  src/internal_modules/roc_packet/sorted_queue.cpp
  src/internal_modules/roc_packet/sorted_queue.h
  src/internal_modules/roc_rtp/populator.cpp
  src/internal_modules/roc_rtp/populator.h
  src/internal_modules/roc_rtp/timestamp_injector.cpp
  src/internal_modules/roc_rtp/timestamp_injector.h
  src/internal_modules/roc_rtp/validator.cpp
  src/internal_modules/roc_rtp/validator.h
  src/internal_modules/roc_status/code_to_str.cpp
  src/internal_modules/roc_status/code_to_str.h
  src/internal_modules/roc_status/status_code.h
  src/public_api/src/sender_encoder.cpp
  src/tests/public_api/test_helpers/proxy.h
  src/tests/roc_audio/test_depacketizer.cpp
  src/tests/roc_audio/test_packetizer.cpp
  src/tests/roc_fec/test_helpers/packet_dispatcher.h
  src/tests/roc_fec/test_writer_reader.cpp
  src/tests/roc_netio/test_udp_io.cpp
  src/tests/roc_node/test_sender_encoder.cpp
  src/tests/roc_packet/test_concurrent_queue.cpp
  src/tests/roc_packet/test_delayed_reader.cpp
  src/tests/roc_packet/test_interleaver.cpp
  src/tests/roc_packet/test_router.cpp
  src/tests/roc_packet/test_sorted_queue.cpp
  src/tests/roc_pipeline/test_helpers/packet_reader.h
  src/tests/roc_pipeline/test_helpers/packet_sender.h
  src/tests/roc_pipeline/test_sender_sink.cpp
  src/tests/roc_pipeline/test_sender_sink_receiver_source.cpp
  src/tests/roc_rtp/test_helpers/status_reader.h
  src/tests/roc_rtp/test_populator.cpp
  src/tests/roc_rtp/test_timestamp_extractor.cpp
  src/tests/roc_rtp/test_timestamp_injector.cpp
  src/tests/roc_rtp/test_validator.cpp
Labels: ready for review

#603 StringBuffer and StringBuilder changes
  src/internal_modules/roc_address/endpoint_uri.h
  src/internal_modules/roc_address/io_uri.h
  src/internal_modules/roc_core/string_buffer.cpp
  src/internal_modules/roc_core/string_buffer.h
  src/internal_modules/roc_core/string_builder.cpp
  src/internal_modules/roc_core/string_builder.h
  src/internal_modules/roc_sdp/session_description.h
  src/internal_modules/roc_sndio/target_sox/roc_sndio/sox_source.h
  src/tests/roc_core/test_string_buffer.cpp
  src/tests/roc_core/test_string_builder.cpp
Labels: needs revision, contribution

#605 Rework status::code_to_str
  src/internal_modules/roc_audio/depacketizer.cpp
  src/internal_modules/roc_fec/reader.cpp
  src/internal_modules/roc_status/code_to_str.cpp
  src/internal_modules/roc_status/code_to_str.h
  src/public_api/src/sender_encoder.cpp
Labels: ready for review

#606 GH-303 Add missed explicit for constructor
  src/tests/roc_audio/test_depacketizer.cpp
Labels: ready for review

#604 Fix in SpeexResampler CTS calculations, also relaxed its tests.
  src/internal_modules/roc_audio/target_speexdsp/roc_audio/speex_resampler.cpp
  src/internal_modules/roc_audio/target_speexdsp/roc_audio/speex_resampler.h
  src/tests/roc_audio/test_resampler.cpp
Labels: needs revision

#612 add script for generating enums in bindings repo (java, go)
  scripts/generate_enums.py
Labels: needs revision

#613 Heap arena ownership guard
  src/internal_modules/roc_core/heap_arena.cpp
  src/internal_modules/roc_core/heap_arena.h
  src/tests/roc_core/test_heap_arena.cpp
Labels: ready for review, contribution

#616 AlignOps EndianOps cpp files
  src/internal_modules/roc_core/align_ops.cpp
  src/internal_modules/roc_core/align_ops.h
  src/internal_modules/roc_core/endian_ops.cpp
  src/internal_modules/roc_core/endian_ops.h
Labels: needs revision, contribution

#611 HashMap implementation extract
  src/internal_modules/roc_core/hashmap.h
  src/internal_modules/roc_core/hashmap_impl.cpp
  src/internal_modules/roc_core/hashmap_impl.h
Labels: needs revision, contribution, hacktoberfest-accepted
