Repository roc-streaming/roc-toolkit, pull requests merged in 2023-12, with the labels that each got.

#653 Clean up FEC tests
  src/tests/roc_fec/test_writer_reader.cpp
Labels: ready for review

#662 Parsing float for duration and size
  docs/sphinx/manuals/roc_copy.rst
  docs/sphinx/manuals/roc_recv.rst
  docs/sphinx/manuals/roc_send.rst
  src/internal_modules/roc_core/parse_units.cpp
  src/tests/roc_core/test_parse_units.cpp
  src/tools/roc_copy/cmdline.ggo
  src/tools/roc_recv/cmdline.ggo
  src/tools/roc_send/cmdline.ggo
Labels: needs revision, contribution

#666 NO_COLOR and FORCE_COLOR env vars support
  docs/man/roc-copy.1
  docs/man/roc-recv.1
  docs/man/roc-send.1
  docs/sphinx/manuals/roc_copy.rst
  docs/sphinx/manuals/roc_recv.rst
  docs/sphinx/manuals/roc_send.rst
  src/internal_modules/roc_core/target_posix_pc/roc_core/console.cpp
Labels: ready for review, contribution

#664 Seqlock implementation extract
  src/internal_modules/roc_core/seqlock.h
  src/internal_modules/roc_core/seqlock_impl.cpp
  src/internal_modules/roc_core/seqlock_impl.h
Labels: ready for review, contribution

#665 Ubuntu 24.04 builds
  .github/workflows/build.yml
  docs/sphinx/development/continuous_integration.rst
  scripts/ci_checks/linux-x86_64/ubuntu-24.04.sh
Labels: ready for review, contribution
