Repository roc-streaming/roc-toolkit, pull requests merged in 2024-07, with the labels that each got.

#743 added test_ring_queue.cpp, modified RingQueue capacity() definition
  src/internal_modules/roc_core/mov_stats.h
  src/internal_modules/roc_core/ring_queue.h
  src/tests/roc_core/test_ring_queue.cpp
Labels: ready for review, contribution

#746 Update icons and images
  docs/images/doxygen_logo.png
  docs/images/icon.png
  docs/images/icon80.png
  docs/images/logo.png
  docs/images/logo80.png
  docs/images/readme_logo.png
  docs/images/sphinx_logo.png
Labels: ready for review

#745 Implement StringList pop_back()
  src/internal_modules/roc_core/string_list.cpp
  src/internal_modules/roc_core/string_list.h
  src/tests/roc_core/test_string_list.cpp
Labels: ready for review, contribution

#733 Dynamic latency adjustment #688
  docs/sphinx/manuals/roc_recv.rst
  src/internal_modules/roc_audio/feedback_monitor.cpp
  src/internal_modules/roc_audio/feedback_monitor.h
  src/internal_modules/roc_audio/freq_estimator.cpp
  src/internal_modules/roc_audio/freq_estimator.h
  src/internal_modules/roc_audio/latency_monitor.cpp
  src/internal_modules/roc_audio/latency_monitor.h
  src/internal_modules/roc_audio/latency_tuner.cpp
  src/internal_modules/roc_audio/latency_tuner.h
  src/internal_modules/roc_core/csv_dumper.cpp
  src/internal_modules/roc_core/csv_dumper.h
  src/internal_modules/roc_packet/ilink_meter.h
  src/internal_modules/roc_pipeline/config.cpp
  src/internal_modules/roc_pipeline/config.h
  src/internal_modules/roc_pipeline/receiver_session.cpp
  src/internal_modules/roc_pipeline/receiver_session.h
  src/internal_modules/roc_pipeline/receiver_session_group.cpp
  src/internal_modules/roc_pipeline/receiver_session_group.h
  src/internal_modules/roc_pipeline/receiver_slot.cpp
  src/internal_modules/roc_pipeline/receiver_slot.h
  src/internal_modules/roc_pipeline/receiver_source.cpp
  src/internal_modules/roc_pipeline/receiver_source.h
  src/internal_modules/roc_pipeline/sender_session.cpp
  src/internal_modules/roc_pipeline/sender_session.h
  src/internal_modules/roc_pipeline/sender_sink.cpp
  src/internal_modules/roc_pipeline/sender_sink.h
  src/internal_modules/roc_pipeline/sender_slot.cpp
  src/internal_modules/roc_pipeline/sender_slot.h
  src/internal_modules/roc_rtcp/loss_estimator.h
  src/internal_modules/roc_rtp/link_meter.cpp
  src/internal_modules/roc_rtp/link_meter.h
  src/public_api/include/roc/config.h
  src/public_api/include/roc/metrics.h
  src/public_api/src/adapters.cpp
  src/tests/public_api/test_loopback_encoder_2_decoder.cpp
  src/tests/public_api/test_loopback_sender_2_receiver.cpp
  src/tests/roc_audio/test_freq_estimator.cpp
  src/tests/roc_pipeline/test_loopback_sink_2_source.cpp
  src/tests/roc_pipeline/test_receiver_endpoint.cpp
  src/tests/roc_pipeline/test_receiver_loop.cpp
  src/tests/roc_pipeline/test_receiver_source.cpp
  src/tests/roc_pipeline/test_sender_endpoint.cpp
  src/tests/roc_pipeline/test_sender_sink.cpp
  src/tests/roc_pipeline/test_session_router.cpp
  src/tests/roc_rtp/test_link_meter.cpp
  src/tools/roc_recv/cmdline.ggo
  src/tools/roc_recv/main.cpp
  src/tools/roc_send/cmdline.ggo
  src/tools/roc_send/main.cpp
Labels: needs revision

#747 Return status code instead of bool in IBlockEncoder & IBlockDecoder
  src/internal_modules/roc_fec/block_reader.cpp
  src/internal_modules/roc_fec/block_reader.h
  src/internal_modules/roc_fec/block_writer.cpp
  src/internal_modules/roc_fec/block_writer.h
  src/internal_modules/roc_fec/iblock_decoder.h
  src/internal_modules/roc_fec/iblock_encoder.h
  src/internal_modules/roc_fec/target_openfec/roc_fec/openfec_decoder.cpp
  src/internal_modules/roc_fec/target_openfec/roc_fec/openfec_decoder.h
  src/internal_modules/roc_fec/target_openfec/roc_fec/openfec_encoder.cpp
  src/internal_modules/roc_fec/target_openfec/roc_fec/openfec_encoder.h
  src/tests/roc_fec/test_block_encoder_decoder.cpp
  src/tests/roc_fec/test_block_writer_reader_errors.cpp
Labels: ready for review, contribution

#760 Implemented Moving Histogram algorithm
  src/internal_modules/roc_core/mov_histogram.h
  src/tests/roc_core/test_mov_histogram.cpp
Labels: review in progress, contribution

#762 Add IDevice::close()
  src/internal_modules/roc_pipeline/receiver_loop.cpp
  src/internal_modules/roc_pipeline/receiver_loop.h
  src/internal_modules/roc_pipeline/receiver_source.cpp
  src/internal_modules/roc_pipeline/receiver_source.h
  src/internal_modules/roc_pipeline/sender_loop.cpp
  src/internal_modules/roc_pipeline/sender_loop.h
  src/internal_modules/roc_pipeline/sender_sink.cpp
  src/internal_modules/roc_pipeline/sender_sink.h
  src/internal_modules/roc_pipeline/transcoder_sink.cpp
  src/internal_modules/roc_pipeline/transcoder_sink.h
  src/internal_modules/roc_pipeline/transcoder_source.cpp
  src/internal_modules/roc_pipeline/transcoder_source.h
  src/internal_modules/roc_sndio/idevice.h
  src/internal_modules/roc_sndio/pump.cpp
  src/internal_modules/roc_sndio/pump.h
  src/internal_modules/roc_sndio/target_pulseaudio/roc_sndio/pulseaudio_device.cpp
  src/internal_modules/roc_sndio/target_pulseaudio/roc_sndio/pulseaudio_device.h
  src/internal_modules/roc_sndio/target_sndfile/roc_sndio/sndfile_sink.cpp
  src/internal_modules/roc_sndio/target_sndfile/roc_sndio/sndfile_sink.h
  src/internal_modules/roc_sndio/target_sndfile/roc_sndio/sndfile_source.cpp
  src/internal_modules/roc_sndio/target_sndfile/roc_sndio/sndfile_source.h
  src/internal_modules/roc_sndio/target_sox/roc_sndio/sox_sink.cpp
  src/internal_modules/roc_sndio/target_sox/roc_sndio/sox_sink.h
  src/internal_modules/roc_sndio/target_sox/roc_sndio/sox_source.cpp
  src/internal_modules/roc_sndio/target_sox/roc_sndio/sox_source.h
  src/internal_modules/roc_sndio/wav_sink.cpp
  src/internal_modules/roc_sndio/wav_sink.h
  src/internal_modules/roc_sndio/wav_source.cpp
  src/internal_modules/roc_sndio/wav_source.h
  src/tests/roc_pipeline/test_helpers/mock_sink.h
  src/tests/roc_pipeline/test_helpers/mock_source.h
  src/tests/roc_sndio/test_backend_sink.cpp
  src/tests/roc_sndio/test_backend_source.cpp
  src/tests/roc_sndio/test_helpers/mock_sink.h
  src/tests/roc_sndio/test_helpers/mock_source.h
Labels: ready for review, contribution
