Repository roc-streaming/roc-toolkit, pull requests merged in 2024-08, with the labels that each got.

#761 Mov quantile
  src/internal_modules/roc_core/mov_quantile.h
  src/tests/roc_core/test_mov_quantile.cpp
Labels: review in progress, contribution

#773 Added more Tests for Moving Histogram Algorithm
  src/tests/roc_core/test_mov_histogram.cpp
Labels: ready for review, contribution

#763 Implemented explicit flushing of buffered samples from sink to file
  src/internal_modules/roc_pipeline/sender_loop.cpp
  src/internal_modules/roc_pipeline/sender_loop.h
  src/internal_modules/roc_pipeline/sender_sink.cpp
  src/internal_modules/roc_pipeline/sender_sink.h
  src/internal_modules/roc_pipeline/transcoder_sink.cpp
  src/internal_modules/roc_pipeline/transcoder_sink.h
  src/internal_modules/roc_sndio/isink.h
  src/internal_modules/roc_sndio/pump.cpp
  src/internal_modules/roc_sndio/target_pulseaudio/roc_sndio/pulseaudio_device.cpp
  src/internal_modules/roc_sndio/target_pulseaudio/roc_sndio/pulseaudio_device.h
  src/internal_modules/roc_sndio/target_sndfile/roc_sndio/sndfile_sink.cpp
  src/internal_modules/roc_sndio/target_sndfile/roc_sndio/sndfile_sink.h
  src/internal_modules/roc_sndio/target_sox/roc_sndio/sox_sink.cpp
  src/internal_modules/roc_sndio/target_sox/roc_sndio/sox_sink.h
  src/internal_modules/roc_sndio/wav_sink.cpp
  src/internal_modules/roc_sndio/wav_sink.h
  src/tests/roc_pipeline/test_helpers/mock_sink.h
  src/tests/roc_sndio/test_helpers/mock_sink.h
Labels: ready for review, contribution

#776 Improve peak jitter calculations
  src/internal_modules/roc_audio/jitter_meter.cpp
  src/internal_modules/roc_audio/jitter_meter.h
  src/internal_modules/roc_audio/latency_tuner.cpp
  src/internal_modules/roc_audio/latency_tuner.h
  src/internal_modules/roc_packet/ilink_meter.h
  src/internal_modules/roc_pipeline/config.cpp
  src/internal_modules/roc_pipeline/config.h
  src/internal_modules/roc_pipeline/receiver_session.cpp
  src/internal_modules/roc_pipeline/sender_session.cpp
  src/internal_modules/roc_rtp/link_meter.cpp
  src/internal_modules/roc_rtp/link_meter.h
  src/internal_modules/roc_stat/mov_aggregate.h
  src/internal_modules/roc_stat/mov_histogram.h
  src/internal_modules/roc_stat/mov_quantile.h
  src/public_api/src/adapters.cpp
  src/tests/roc_pipeline/test_helpers/control_writer.h
  src/tests/roc_pipeline/test_loopback_sink_2_source.cpp
  src/tests/roc_pipeline/test_receiver_source.cpp
  src/tests/roc_pipeline/test_sender_sink.cpp
  src/tests/roc_rtp/test_link_meter.cpp
Labels: ready for review
